doctrine_cache:
    providers:
        serializer_metadata:
            file_system:
                extension: .cache
                directory: "%kernel.root_dir%/../var/cache/%kernel.environment%/serializer_metadata"
        image_server:
            file_system:
                extension: .cache
                directory: "%kernel.root_dir%/../var/cache/%kernel.environment%/image_server"
        geocoding:
            file_system:
                extension: .cache
                directory: "%kernel.root_dir%/../var/cache/%kernel.environment%/geocoding"
        device_detector:
            file_system:
                extension: .cache
                directory: ""
