language: php
php:
  - '7.0'

addons:
  apt:
    packages:
      - python-pip

before_install:
  - sudo apt-get update -q
  - sudo apt-get install python-pip
  - sudo pip install sphinx

jobs:
  include:
    - script: "echo Unit Tests"
    - stage: "deploy"
      script: 'cd docs && make html'
      deploy:
        provider: s3
        access_key_id: "$S3_DOCUMENTATION_ID"
        secret_access_key: "$S3_DOCUMENTATION_KEY"
        bucket: "www.audiencehero.org"
        skip_cleanup: true
        region: "eu-west-1"
        local_dir: _build/html
        acl: public_read
