version: '3.5'

services:
    db:
        image: postgres:9.6
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_USER: audiencehero
            POSTGRES_PASSWORD: audiencehero
            POSTGRES_DB: audiencehero
        ports:
            - "5432:5432"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        environment:
            RABBITMQ_DEFAULT_VHOST: audiencehero

    php:
        build:
            context: ./
            dockerfile: ./Dockerfile
        env_file:
            - ./.env
        depends_on:
            - db
            - rabbitmq
        volumes:
            - ./:/srv/audiencehero:rw,cached

    node:
        build:
            context: ./
            dockerfile: ./Dockerfile.node
        env_file:
            - ./.env
        volumes:
            - ./:/srv/audiencehero:rw,cached

    nginx:
        image: nginx:1.13-alpine
        env_file:
            - ./.env
        depends_on:
            - php
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/conf.d/default.template:/etc/nginx/conf.d/default.template
            - ./web:/srv/audiencehero/web:ro

volumes:
    db-data: {}
