services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AudienceHero\Bundle\AcquisitionFreeDownloadBundle\:
        resource: '../../*'
        exclude: '../../{Action,Controller,Entity,Repository,Tests}'

    AudienceHero\Bundle\AcquisitionFreeDownloadBundle\Action\:
        public: true
        resource: '../../Action/*'
        tags: ['controller.service_arguments']

    AudienceHero\Bundle\AcquisitionFreeDownloadBundle\Repository\AcquisitionFreeDownloadRepository:
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AudienceHero\Bundle\AcquisitionFreeDownloadBundle\Entity\AcquisitionFreeDownload
