_audience_hero_file_action:
    resource: "@AudienceHeroFileBundle/Action"
    type: annotation

_audience_hero_file_controller:
    resource: "@AudienceHeroFileBundle/Controller"
    type: annotation
