_audience_hero_core_spa:
  resource: '@AudienceHeroCoreBundle/Controller'
  type: annotation

_audience_hero_core_controller:
    resource: "@AudienceHeroCoreBundle/Controller/"
    type:     annotation
    prefix:   /

_audience_hero_core_action:
    resource: "@AudienceHeroCoreBundle/Action/"
    type:     annotation
    prefix:   /

