imports:
    - { resource: config_dev.yml }

parameters:
    mopro_domain: localhost

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    translator:
        enabled: false
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        # Appending _test to the database_name parameter is a safeguard in case of command execution on production
        dbname:   "%database_name%_test"

ewz_recaptcha:
    enabled: false

audience_hero_file:
    filesystem: local
    base: upload
