imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

audience_hero_core:
    mailer:
        adapter: mailgun

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      file
            buffer_size: 50
        file:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

swiftmailer:
    disable_delivery: false

audience_hero_file:
    filesystem: s3