api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api' # Optional

_audience_hero_promo_action:
    resource: "@AudienceHeroPromoBundle/Action"
    type: annotation

_audience_hero_contacts_actions:
    resource: "@AudienceHeroContactBundle/Action/"
    type:     annotation
    prefix:   /

_audience_hero_podcast_actions:
    resource: "@AudienceHeroPodcastBundle/Action"
    type: annotation

_audience_hero_acquisition_free_download:
    resource: "@AudienceHeroAcquisitionFreeDownloadBundle/Action"
    type: annotation

_audience_hero_file_action:
    resource: "@AudienceHeroFileBundle/Action"
    type: annotation

_audience_hero_file_controller:
    resource: "@AudienceHeroFileBundle/Controller"
    type: annotation

_audience_hero_image_server:
    resource: "@AudienceHeroImageServerBundle/Action"
    prefix:   /

_audience_hero_mailing_actions:
    resource: "@AudienceHeroMailingCampaignBundle/Action/"
    type: annotation


_audience_hero_core_controller:
    resource: "@AudienceHeroCoreBundle/Controller/"
    type:     annotation
    prefix:   /

_audience_hero_core_action:
    resource: "@AudienceHeroCoreBundle/Action/"
    type:     annotation
    prefix:   /

_audience_hero_spa:
  resource: '@AudienceHeroCoreBundle/Controller'
  type: annotation

