<?php

return [
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true, 'test' => true],
    Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => ['dev' => true, 'test' => true],
    Hautelook\AliceBundle\HautelookAliceBundle::class => ['dev' => true, 'test' => true],
    Liip\FunctionalTestBundle\LiipFunctionalTestBundle::class => ['dev' => true, 'test' => true],
    Http\HttplugBundle\HttplugBundle::class => ['all' => true],
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Enqueue\Bundle\EnqueueBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    Misd\PhoneNumberBundle\MisdPhoneNumberBundle::class => ['all' => true],
    MarcW\RssWriter\Bundle\MarcWRssWriterBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Sensio\Bundle\DistributionBundle\SensioDistributionBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Sylius\Bundle\MailerBundle\SyliusMailerBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    Bazinga\GeocoderBundle\BazingaGeocoderBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    AudienceHero\Bundle\CoreBundle\AudienceHeroCoreBundle::class => ['all' => true],
    AudienceHero\Bundle\AcquisitionFreeDownloadBundle\AudienceHeroAcquisitionFreeDownloadBundle::class => ['all' => true],
    AudienceHero\Bundle\ActivityBundle\AudienceHeroActivityBundle::class => ['all' => true],
    AudienceHero\Bundle\ContactBundle\AudienceHeroContactBundle::class => ['all' => true],
    AudienceHero\Bundle\FOSUserBundle\AudienceHeroFOSUserBundle::class => ['all' => true],
    AudienceHero\Bundle\ContactImportCsvBundle\AudienceHeroContactImportCsvBundle::class => ['all' => true],
    AudienceHero\Bundle\FileBundle\AudienceHeroFileBundle::class => ['all' => true],
    AudienceHero\Bundle\ImageServerBundle\AudienceHeroImageServerBundle::class => ['all' => true],
    AudienceHero\Bundle\MailingCampaignBundle\AudienceHeroMailingCampaignBundle::class => ['all' => true],
    AudienceHero\Bundle\PodcastBundle\AudienceHeroPodcastBundle::class => ['all' => true],
    AudienceHero\Bundle\PromoBundle\AudienceHeroPromoBundle::class => ['all' => true],
    AudienceHero\Bundle\SitemapBundle\AudienceHeroSitemapBundle::class => ['all' => true],
];
